version: 2
jobs:
  build:
    working_directory: ~/workspace
    docker:
      - image: python:3.7.4

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-{{ arch }}-{{ checksum "requirements.txt" }}
            - v1-{{ arch }}
      - run:
          name: Install retry command
          command: |
              ./.circleci/setup-retry.sh
      - run:
          name: Install dependencies
          command: |
            retry -- pip install -r requirements.txt
            retry -- pip install -r requirements-dev.txt
      - run:
          name: Test
          command: |
            python -m py_compile app.py
            retry -- python -m pytest
      - save_cache:
          key: v1-{{ arch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.cache/pip/
      - run:
          name: Notify deploy started
          command: |
            if [ "$CIRCLE_BRANCH" = 'master' ]; then
              retry -- pip3 install -q slackweb
              python3 scripts/notify.py started
            fi
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./.circleci/setup-heroku.sh
              retry -- heroku git:remote --app eg-web-redirect
              retry -- git push -f heroku master
            fi
      - run:
          name: Notify deploy successful
          command: |
            if [ "$CIRCLE_BRANCH" = 'master' ]; then
              retry -- pip3 install -q slackweb
              python3 scripts/notify.py successful
            fi
      - run:
          name: Notify deploy failed
          command: |
            if [ "$CIRCLE_BRANCH" = 'master' ]; then
              retry -- pip3 install -q slackweb
              python3 scripts/notify.py failed
            fi
          when: on_fail

